[project]
name = "notifications"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "enums>=0.0.2",
    "fastapi>=0.129.0",
    "pydantic>=2.12.5",
    "tortoise-orm>=1.1.4",
    "uvicorn>=0.41.0",
]
